import './globals.scss';
import './1920.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppBar from './(components)/AppBar';
import Footer from './(components)/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
